import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, AlertTriangle, Bell, BookOpen, CalendarDays, ChevronDown, Database, FileText, Home, List, PauseCircle, Plus, RefreshCw, Rss, Search, Settings, ShieldCheck, Users } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import './styles.css';

const API = import.meta.env.VITE_API_BASE_URL || '/api';
const nav = [
  ['overview', '首页概览', Home], ['feeds', '订阅管理', FileText], ['groups', '订阅组管理', Users],
  ['entries', '全局动态', List], ['status', '源状态', ShieldCheck], ['docs', 'API 文档', BookOpen]
];
const statusText = { normal: '正常', fetch_failed: '抓取失败', parse_error: '解析异常', disabled: '已停用' };
const statusClass = { normal: 'ok', fetch_failed: 'bad', parse_error: 'warn', disabled: 'muted' };

function useApi(path, fallback) {
  const [data, setData] = useState(fallback);
  const [loading, setLoading] = useState(true);
  const reload = () => { setLoading(true); fetch(API + path).then(r => r.json()).then(setData).finally(() => setLoading(false)); };
  useEffect(reload, [path]);
  return { data, loading, reload };
}
function fmt(v) { return v ? String(v).replace('T', ' ').slice(0, 19) : '-'; }
function StatCard({ icon: Icon, label, value, hint, tone = 'blue' }) { return <div className="stat-card"><div className={'orb '+tone}><Icon size={30}/></div><div><p>{label}</p><b>{value}</b><span>{hint}</span></div></div>; }
function Shell({ page, setPage, children }) { return <div className="app"><aside><div className="brand"><Database/><b>数据库动态 RSS 管理平台</b></div><nav>{nav.map(([id, label, Icon]) => <button key={id} onClick={() => setPage(id)} className={page===id?'active':''}><Icon size={20}/>{label}</button>)}</nav><div className="collapse">≪　收起菜单</div></aside><main><Topbar/>{children}</main></div>; }
function Topbar(){ return <div className="topbar"><div className="global-search"><input placeholder="搜索订阅源、订阅组或动态..."/><Search size={20}/></div><Bell/><span className="badge">12</span><div className="avatar"></div><ChevronDown size={16}/></div>; }
function PageTitle({title, sub}){return <header className="page-title"><h1>{title}</h1>{sub&&<p>{sub}</p>}</header>}
function StatusPill({status, enabled=true}){ const s = enabled ? status : 'disabled'; return <span className={'pill '+(statusClass[s]||'muted')}>{statusText[s]||s}</span> }

function Overview(){
 const {data} = useApi('/overview', {stats:{}, trend:[], recent_feeds:[], groups:[], abnormal_feeds:[]});
 const trend = normalizeTrend(data.trend);
 return <><PageTitle title="首页概览"/><section className="grid4"><StatCard icon={FileText} label="今日新增动态" value={data.stats.today_entries ?? 0} hint="今日新增的动态条目总数"/><StatCard icon={Rss} label="订阅源总数" value={data.stats.feed_count ?? 0} hint="当前已配置的 RSS 订阅源总数" tone="green"/><StatCard icon={Users} label="订阅组总数" value={data.stats.group_count ?? 0} hint="当前已创建的订阅组总数" tone="purple"/><StatCard icon={AlertTriangle} label="异常订阅源" value={data.stats.abnormal_count ?? 0} hint="当前存在异常的订阅源数量" tone="red"/></section>
 <section className="two-col"><div className="panel"><div className="panel-head"><h2>最近 7 天动态趋势</h2><button>近 7 天⌄</button></div><ResponsiveContainer width="100%" height={240}><AreaChart data={trend}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2563eb" stopOpacity={.25}/><stop offset="95%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e8edf6"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Area dataKey="count" stroke="#2563eb" fill="url(#g)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div><RecentFeeds feeds={data.recent_feeds}/></section>
 <div className="panel"><div className="panel-head"><h2>常用订阅组</h2><a>管理订阅组</a></div><div className="cards">{data.groups.map((g,i)=><div className="mini" key={g.id}><div className={'square s'+i}>{['▰','◆','♜','✣','◒'][i]}</div><b>{g.name}</b><p>包含订阅数 <span>{g.feed_count}</span></p><p>今日新增 <span>{g.today_new||0}</span></p><p>最近更新时间 <span>{fmt(g.latest_update)}</span></p><button>查看详情</button></div>)}</div></div><Abnormal feeds={data.abnormal_feeds}/></>;
}
function normalizeTrend(rows){ const map=Object.fromEntries((rows||[]).map(x=>[x.date,x.count])); return [...Array(7)].map((_,i)=>{const d=new Date(); d.setDate(d.getDate()-6+i); const k=d.toISOString().slice(0,10); return {date:k.slice(5), count:map[k]||0};}); }
function RecentFeeds({feeds}){return <div className="panel"><div className="panel-head"><h2>最近更新订阅源</h2><a>查看更多</a></div><table><thead><tr><th>订阅源名称</th><th>最近更新时间</th><th>今日新增</th></tr></thead><tbody>{feeds.map(f=><tr key={f.id}><td><Rss size={15}/>{f.name}</td><td>{fmt(f.latest_item_published_at)}</td><td className="blue">{f.today_new||0}</td></tr>)}</tbody></table></div>}
function Abnormal({feeds}){return <div className="panel"><div className="panel-head"><h2>异常订阅源</h2><a>查看更多</a></div><table><thead><tr><th>订阅名称</th><th>厂商</th><th>产品</th><th>异常类型</th><th>最近抓取时间</th><th>操作</th></tr></thead><tbody>{feeds.map(f=><tr key={f.id}><td>{f.name}</td><td>{f.vendor}</td><td>{f.product}</td><td><StatusPill status={f.status} enabled={f.enabled}/></td><td>{fmt(f.last_fetched_at)}</td><td><a>查看</a><a>重试</a></td></tr>)}</tbody></table></div>}

function Feeds(){
 const [q,setQ]=useState(''); const {data,reload}=useApi('/feeds'+(q?'?keyword='+q:''), []);
 const stats = useMemo(()=>({total:data.length, ok:data.filter(x=>x.status==='normal'&&x.enabled).length, bad:data.filter(x=>['fetch_failed','parse_error'].includes(x.status)).length, off:data.filter(x=>!x.enabled).length}),[data]);
 const refresh = (id)=>fetch(`${API}/feeds/${id}/refresh`,{method:'POST'}).then(reload);
 return <><PageTitle title="订阅管理" sub="统一管理所有数据库 RSS 订阅源，支持搜索、筛选、查看状态与维护操作"/><Toolbar q={q} setQ={setQ} primary="新增订阅"/><section className="grid4"><StatCard icon={Rss} label="订阅源总数" value={stats.total} hint="所有订阅源数量"/><StatCard icon={ShieldCheck} label="正常订阅源" value={stats.ok} hint="运行正常的订阅源" tone="green"/><StatCard icon={AlertTriangle} label="异常订阅源" value={stats.bad} hint="存在异常的订阅源" tone="red"/><StatCard icon={PauseCircle} label="停用订阅源" value={stats.off} hint="已停用的订阅源" tone="gray"/></section><div className="panel"><div className="panel-head"><h2>RSS 订阅列表</h2><div><button>导出</button><button onClick={reload}><RefreshCw size={16}/>刷新列表</button></div></div><table><thead><tr><th>订阅名称</th><th>厂商</th><th>产品</th><th>数据库类型</th><th>RSS URL</th><th>最近更新时间</th><th>最近抓取时间</th><th>状态</th><th>所属订阅组</th><th>操作</th></tr></thead><tbody>{data.map(f=><tr key={f.id}><td><Rss size={15}/>{f.name}</td><td>{f.vendor}</td><td>{f.product}</td><td>{f.db_type}</td><td className="clip">{f.rss_url}</td><td>{fmt(f.latest_item_published_at)}</td><td>{fmt(f.last_fetched_at)}</td><td><StatusPill status={f.status} enabled={f.enabled}/></td><td>{f.groups||'-'}</td><td className="actions"><a>查看</a><a>编辑</a><a className="danger">删除</a><a onClick={()=>refresh(f.id)}>刷新</a></td></tr>)}</tbody></table><p className="count">共 {data.length} 条</p></div></>;
}
function Toolbar({q,setQ,primary}){return <div className="toolbar"><button className="primary"><Plus size={18}/>{primary}</button><button>批量导入</button><label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索订阅名称、厂商、产品或 URL"/><Search size={18}/></label><button>厂商⌄</button><button>产品⌄</button><button>数据库类型⌄</button><button>状态⌄</button><button><RefreshCw size={16}/>重置筛选</button></div>}

function Groups(){ const {data}=useApi('/groups', []); return <><PageTitle title="订阅组管理" sub="将多个 RSS 源组合成主题集合，支持聚合、按源分组和日历视图"/><div className="toolbar"><button className="primary"><Plus size={18}/>新增订阅组</button><label><input placeholder="搜索订阅组名称或描述"/><Search size={18}/></label><button>状态⌄</button></div><section className="group-grid">{data.map((g,i)=><div className="group-card" key={g.id}><div className={'square s'+i}>{['●','◆','♜','✣','◒'][i%5]}</div><h3>{g.name}</h3><p>{g.description}</p><div><span>包含订阅数</span><b>{g.feed_count}</b></div><div><span>今日新增</span><b>{g.today_new||0}</b></div><div><span>最近更新时间</span><b>{fmt(g.latest_update)}</b></div><StatusPill status="normal" enabled={g.enabled}/><button>查看详情</button></div>)}</section><GroupDetail id={3}/></> }
function GroupDetail({id}){ const {data:g}=useApi(`/groups/${id}`, {feeds:[]}); const {data:e}=useApi(`/groups/${id}/entries`, {items:[]}); return <div className="detail"><div className="detail-head"><div className="big-icon"><Users/></div><div><h2>{g.name||'PostgreSQL 生态'}</h2><p>{g.description}</p></div><button>返回列表</button><button>编辑订阅组</button><button className="primary">管理订阅源</button></div><div className="panel"><div className="tabs"><button className="active"><List size={16}/>聚合列表</button><button>按源分组</button><button>日历视图</button><input placeholder="搜索标题、摘要或来源订阅源"/></div><EntryTable items={e.items}/></div></div> }
function Entries(){ const {data}=useApi('/entries', {items:[]}); const {data:cal}=useApi('/calendar', []); return <><PageTitle title="全局动态" sub="查看平台内所有 RSS 动态，支持搜索、筛选与日历视图"/><div className="panel"><div className="tabs"><button className="active">全部条目</button><button>全局日历</button><input placeholder="搜索标题和摘要"/></div><EntryTable items={data.items}/></div><CalendarView days={cal}/></>}
function EntryTable({items}){return <table><thead><tr><th>标题</th><th>来源订阅源</th><th>厂商</th><th>产品</th><th>发布时间</th><th>摘要</th><th>原文链接</th><th>操作</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.title}</td><td><span className="source">{x.feed_name}</span></td><td>{x.vendor}</td><td>{x.product}</td><td>{fmt(x.published_at)}</td><td>{x.summary}</td><td><a href={x.link} target="_blank">查看原文</a></td><td><button>详情</button></td></tr>)}</tbody></table>}
function CalendarView({days}){ const max = Math.max(1,...days.map(d=>d.count)); return <div className="panel calendar"><div className="panel-head"><h2>日历视图</h2><button><CalendarDays size={16}/>月视图</button></div><div className="month">{[...Array(35)].map((_,i)=>{const d=days[i%days.length]||{date:'',count:0,items:[]};return <div className="day" key={i}><b>{i+1}</b>{d.count>0&&<em style={{height:20+d.count/max*60}}>{d.count}</em>}<small>{d.items?.[0]?.title}</small></div>})}</div></div>}
function Status(){ const {data:feeds}=useApi('/feeds', []); const {data:logs}=useApi('/fetch-logs', []); return <><PageTitle title="源状态" sub="查看 RSS 源健康状态与最近抓取记录"/><div className="panel"><h2>订阅源状态</h2><table><tbody>{feeds.map(f=><tr key={f.id}><td>{f.name}</td><td>{f.vendor}</td><td><StatusPill status={f.status} enabled={f.enabled}/></td><td>{f.last_error||'最近抓取成功'}</td><td>{fmt(f.last_fetched_at)}</td></tr>)}</tbody></table></div><div className="panel"><h2>抓取记录</h2><table><thead><tr><th>抓取时间</th><th>订阅源</th><th>结果</th><th>新增条目数</th><th>总条目数</th><th>错误信息</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{fmt(l.started_at)}</td><td>{l.feed_name}</td><td><StatusPill status={l.result==='success'?'normal':'fetch_failed'}/></td><td>{l.new_entries}</td><td>{l.total_entries}</td><td>{l.error_message}</td></tr>)}</tbody></table></div></>}
function Docs(){ const endpoints=['GET /api/feeds','GET /api/feeds/{id}','GET /api/feeds/{id}/entries','GET /api/feeds/{id}/calendar','GET /api/groups','GET /api/groups/{id}/entries','GET /api/groups/{id}/entries-by-source','GET /api/groups/{id}/calendar','GET /api/entries','GET /api/calendar','GET /api/fetch-logs']; return <><PageTitle title="API 文档" sub="供 OpenClaw / Codex / Agent Skill 调用的结构化查询接口"/><div className="panel api-list">{endpoints.map(x=><code key={x}>{x}</code>)}</div></>}
function App(){ const [page,setPage]=useState('overview'); const C={overview:Overview,feeds:Feeds,groups:Groups,entries:Entries,status:Status,docs:Docs}[page]; return <Shell page={page} setPage={setPage}><C/></Shell> }
createRoot(document.getElementById('root')).render(<App/>);
